name: J2MC_Teleport
main: to.joe.j2mc.teleport.J2MC_Teleport
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Teleport module.
commands:
  home:
    description: go home
    usage: /home <home name>
    permission: j2mc.teleport.home.visit
    permission-message: You may not use homes
  protectme:
    description: protect yourself from teleports
    usage: /protectme
    permission: j2mc.teleport.protectable
    permission-message: You may not protect yourself
  sethome:
    description: set a home
    usage: /sethome <home name>
    permission: j2mc.teleport.home.visit
    permission-message: You may not use homes
  spawn:
    description: go to spawn
    usage: /spawn
    permission: j2mc.teleport.spawn.visit
    permission-message: No spawn for you
  tp:
    aliases: ['teleport']
    description: teleport to someone
    usage: /tp <player name>
    permission: j2mc.teleport.to
    permission-message: You may not teleport
  warp:
    description: warp
    usage: |
            /warp
            /warp <warp name>
    permission: j2mc.teleport.warp.visit
    permission-message: You may not warp
  hi:
    description: they see me invading your homes
    usage: |
            /hi <playername>
            /hi <playername> <home name>
    permission: j2mc.teleport.home.invade
    permission-message: Hello to you too
permissions:
  j2mc.teleport.home.visit:
    description: Homes
  j2mc.teleport.home.invade:
    description muahahaah
  j2mc.teleport.protectable:
    description: TP Protect
  j2mc.teleport.spawn.visit:
    description: Visit spawn
  j2mc.teleport.spawn.send:
    description: Send others to spawn
  j2mc.teleport.to:
    description: teleport
  j2mc.teleport.override:
    description: able to teleport to anyone
  j2mc.teleport.warp.visit:
    description: Warp warp warp
  j2mc.teleport.home.invade:
    description: Evil evilness
  j2mc.teleport.normaluser:
    description: Normal
    children:
      j2mc.teleport.home.visit: true
      j2mc.teleport.spawn.visit: true
      j2mc.teleport.to: true
      j2mc.teleport.warp.visit: true
  j2mc.teleport.admin:
    description: Admin
    children:
      j2mc.teleport.home.invade: true
      j2mc.teleport.spawn.send: true
      j2mc.teleport.override: true
      j2mc.teleport.home.invade: true